"""create users table

Revision ID: 4d9f6f49ad6f
Revises: 
Create Date: 2026-02-21 21:01:26.403336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9f6f49ad6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='user_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###

    # Seed bootstrap admin user — password: AdminPass123
    op.execute(
        sa.text(
            "INSERT INTO users (email, username, password_hash, role, status) "
            "VALUES ("
            "  'admin@example.com',"
            "  'admin',"
            "  '$2b$12$VPfcPH.UI.HiD/Q.etmT4OpaIJuskUGZxnJgM8nFkEKZfUMpvqhgO',"
            "  'ADMIN',"
            "  'ACTIVE'"
            ")"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # Drop enum types created with the table
    op.execute(sa.text("DROP TYPE IF EXISTS user_role"))
    op.execute(sa.text("DROP TYPE IF EXISTS user_status"))
    # ### end Alembic commands ###
